In [23]:
import pandas as pd

In [24]:
read = pd.read_csv("data_sets\\bank.csv")

In [25]:
read

     age          job   marital  education  balance housing loan
0     58   management   married        NaN     2143     yes   no
1     44   technician    single        NaN     1506     yes   no
2     33      unknown    single    unknown        1      no   no
3     35   management   married   tertiary      231     yes   no
4     28   management    single   tertiary      447     yes  yes
..   ...          ...       ...        ...      ...     ...  ...
146   59  blue-collar   married  secondary       57     yes   no
147   33     services   married        NaN       22     yes   no
148   56  blue-collar  divorced    primary        8     yes   no
149   48   unemployed   married  secondary      293     yes   no
150   43     services   married    primary        3     yes   no

[151 rows x 7 columns]

In [26]:
read.shape

(151, 7)

In [27]:
read.columns

Index(['age', 'job', 'marital', 'education', 'balance', 'housing', 'loan'], dtype='object')

In [28]:
read.head()

   age         job  marital education  balance housing loan
0   58  management  married       NaN     2143     yes   no
1   44  technician   single       NaN     1506     yes   no
2   33     unknown   single   unknown        1      no   no
3   35  management  married  tertiary      231     yes   no
4   28  management   single  tertiary      447     yes  yes

In [29]:
read.tail()

     age          job   marital  education  balance housing loan
146   59  blue-collar   married  secondary       57     yes   no
147   33     services   married        NaN       22     yes   no
148   56  blue-collar  divorced    primary        8     yes   no
149   48   unemployed   married  secondary      293     yes   no
150   43     services   married    primary        3     yes   no

In [56]:
read.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        151 non-null    int64
 1   job        151 non-null    object
 2   marital    151 non-null    object
 3   education  145 non-null    object
 4   balance    151 non-null    int64
 5   housing    151 non-null    object
 6   loan       151 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.4+ KB

In [48]:
read.describe(include="all")

               age          job  marital  education       balance housing loan
count   151.000000          151      151        145    151.000000     151  151
unique         NaN           11        3          4           NaN       2    2
top            NaN  blue-collar  married  secondary           NaN     yes   no
freq           NaN           35       94         81           NaN     128  123
mean     45.735099          NaN      NaN        NaN    502.357616     NaN  NaN
std      10.445862          NaN      NaN        NaN   1532.194580     NaN  NaN
min      23.000000          NaN      NaN        NaN   -674.000000     NaN  NaN
25%      36.500000          NaN      NaN        NaN      6.500000     NaN  NaN
50%      46.000000          NaN      NaN        NaN     96.000000     NaN  NaN
75%      55.000000          NaN      NaN        NaN    364.500000     NaN  NaN
max      60.000000          NaN      NaN        NaN  12223.000000     NaN  NaN

In [49]:
read["marital"].value_counts(dropna=False)

marital
married     94
single      35
divorced    22
Name: count, dtype: int64

In [50]:
read["education"].value_counts(dropna=False)

education
secondary    81
tertiary     29
primary      21
unknown      14
NaN           6
Name: count, dtype: int64

In [51]:
read["loan"].value_counts(dropna=False)

loan
no     123
yes     28
Name: count, dtype: int64

In [52]:
print(read.duplicated().sum())

4

In [64]:
read[(read["marital"] == "married") & (read["housing"] == "yes") & (read["loan"] == "yes")]

     age            job  marital  education  balance housing loan
18    28    blue-collar  married  secondary      723     yes  yes
22    40        retired  married    primary        0     yes  yes
25    52   entrepreneur  married  secondary      113     yes  yes
30    60         admin.  married  secondary       39     yes  yes
70    57    blue-collar  married  secondary     5935     yes  yes
71    31       services  married  secondary       25     yes  yes
72    54     management  married  secondary      282     yes  yes
84    46  self-employed  married   tertiary      137     yes  yes
92    30     technician  married  secondary      152     yes  yes
96    36     management  married   tertiary      101     yes  yes
113   56  self-employed  married    primary      -34     yes  yes
124   43       services  married  secondary       41     yes  yes
129   34       services  married  secondary      -16     yes  yes